version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/multi-step-form-app/
    docker: 
      - image: circleci/node:10.16.3
    
    steps:
      - run: 
          name: Install Dependencies
          command: npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build react app
          command: npm run build
      - run: 
          name: Install Surge
          command: npm install -g surge
      - run:
          name: Deoloy to Surge
          command: surge ./build https://multistepformbyhaseebahmed.surge.sh --token ${SURGE_SECRET}


